#!/bin/bash

command=$1

# ddocker exec <CONTAINER_NAME>
if [ "${command}" = "exec" ]; then
    docker exec -ti $2 /bin/bash

# ddocker create
elif [ "${command}" = "create" ]; then
    python $DIST_DOCKER_PATH/dist_docker_create.py

# ddocker run <CPU_NUM> <MEM> <GPU_IDX> <IMG_NAME> <CONTAINER_NAME> <COMMAND_NAME>
elif [ "${command}" = "run" ]; then
    python $DIST_DOCKER_PATH/dist_docker_run.py $2 $3 $4 $5 $6 $7 "${@:8}"

else
    docker "${@:1}"
fi

